### PR TITLE
feat(api): add set_editor_info

### PR DESCRIPTION
**Pull request by MunifTanjim**

### CODE REVIEW

**Comment by zbirenbaum** [comment]
I hardcoded the editor info intentionally for spoofing purposes when I was debugging some issues that weren't present in copilot.vim, as having as much as possible be the same was helpful. I kept it in case microsoft pulls something like what they did with pylance. Since unlike that scenario, neovim being the parent process is both acceptable and expected, the editor info is the place they are most likely to add runtime checks if they decide only "Microsoft approved" usage of copilot is acceptable. 

I'm good with merging this since reverting to a hardcoded version is easy and it seems to just be used for either telemetry or nothing at all right now when looking at the internals, but I think we should wait until after the higher priority PRs are merged to avoid conflicts.

**Comment by MunifTanjim** [comment]
Reverted the `editorPluginInfo` changes. I think keeping original `editorInfo` shouldn't be an issue?

**Comment by zbirenbaum** [comment]
I think I may have misread something in there,  sorry it’s a bit late here and I’ve been coding too long lol. I just reread the changes and it looks good the way it is right now, so I can merge this if you’d like, or we can wait until after panel is figured out so you don’t have to rebase.

**Comment by MunifTanjim** [comment]
No worries 😃

These are just small PRs, and won't conflict with the Panel one. We can merge this without waiting for that big one.

And take rest man.

**Pull request merged**
