### PR TITLE
fix apply_text_edits implicit bufnr 

### LINKED ISSUE #273: Autocompleting suggestion broken after latest Neovim update
After updating Neovim, I'm getting the following error when trying to autocomplete:

```
E5108: Error executing lua: ...vim/HEAD-0fcbda5/share/nvim/runtime/lua/vim/lsp/util.lua:423: Explicit buffer number is required
stack traceback:
	[C]: in function 'assert'
	...vim/HEAD-0fcbda5/share/nvim/runtime/lua/vim/lsp/util.lua:423: in function 'apply_text_edits'
	...l/share/nvim/lazy/copilot.lua/lua/copilot/suggestion.lua:487: in function <...l/share/nvim/lazy/copilot.lua/lua/copilot/suggestion.lua:445>
```

It is almost definitely related to this change: https://github.com/neovim/neovim/pull/27614, and I think the fix would be to pass the current buffer [here](https://github.com/zbirenbaum/copilot.lua/blob/master/lua/copilot/suggestion.lua#L487), but I don't know enough about Lua to be 100% sure.

### PR DESCRIPTION
**Pull request by mosheavni**
fixes #273

### CODE REVIEW

**Comment by pedro757** [comment]
It works for me! thank you!

**Comment by TechDufus** [comment]
Came here to confirm. Nice job @mosheavni!
🎉🎉

**Comment by AstrickHarren** [comment]
Works for me!

**Comment by MariaSolOs** [comment]
@MunifTanjim @zbirenbaum could we please merge this soonish? :)

**Comment by mvaldes14** [comment]
LGTM - please merge.
Need my copilot.

**Comment by zbirenbaum** [comment]
Looks great, thanks for the PR!

**Pull request merged**
