### PR TITLE
fix: make root directory detection dynamic

### LINKED ISSUE #212: LSP functionality detects incorrect root directory
I use LazyVim, which includes several key mappings, for instance for searching in the root directory, that rely on the LSP client detecting the correct root directory. This is the function LazyVim uses: https://github.com/LazyVim/LazyVim/blob/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/util/init.lua#L56-L89

But it seems like the Copilot LSP server is reporting my home directory as the root directory for every file it attaches to. This is for instance the result of calling `:LspInfo` from a `Makefile` in one of my projects.

```
 Language client log: /home/<user>/.local/state/nvim/lsp.log
 Detected filetype:   make
 
 1 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, bufnr: [26, 24])
 	filetypes:       
 	autostart:       false
 	root directory:  /home/<user>
 	cmd:             node /home/<user>/.local/share/nvim/lazy/copilot.lua/copilot/index.js

```

So when Copilot is the only LSP server attached to a file, I end up searching directly in my home directory instead of the project directory.

This is the default setup LazyVim uses for copilot, which I use: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/coding/copilot.lua

If I disable the plugin, then everything works fine because lazyvim then just uses cwd.

Maybe it would be possible to expose a `root_dir` setting just like many of the servers in lspconfig do (https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md)?

A possible interface might be:

```
require('copilot').setup({
  server_opts_overrides = {
    root_dir = require("lspconfig.util").root_pattern(".git"),
  },
})
```

Or I guess the server could just not report the root directory, or default to `vim.loop.cwd()`. I'm not sure exactly if that would work.

### PR DESCRIPTION
**Pull request by jolars**
Fixes #212 

Instead of calling `vim.loop.cwd()` when the plugin is initialized, this pull request calls whatever function is stored in the config as `get_root` every time the LSP attaches to a buffer. I've set this to `require("lspconfig.util").find_git_ancestor` by default, which seems like a reasonable default.

I guess we might need to update the installation instructions, since we now depend on `lspconfig`, or perhaps it would be better just to set a different default (`vim.loop.cwd()`, but called every time the server is updated, maybe).

### CODE REVIEW

**Comment by tris203** [comment]
@zbirenbaum sorry to ping you twice in one day
but there is something odd with this, it has broken copilot for me massively

I am getting lots of duplicate client errors now

**Comment by zbirenbaum** [comment]
> @zbirenbaum sorry to ping you twice in one day
> 
> but there is something odd with this, it has broken copilot for me massively
> 
> 
> 
> I am getting lots of duplicate client errors now

No worries. I didn't run into an issue testing but I was a little apprehensive about this patch since detection can really mess things up historically. I reverted it just now and will review this patch and detection in general more later.

**Comment by shermanjoshua** [comment]
Not that you needed any more validation, but just in case I can provide any information - the revert of this fixed my situation as well. 

I noticed the problem a while back (a few months, which makes tons of sense now) but didn't do much research because I just uninstalled temporarily and moved on with my life, thinking I'd take a look later. When I finally came back to it this weekend and tried to dig in I gathered the information I could. While I was troubleshooting I ran the Lazy.nvim 'update all' command several times and didn't get the patch. As I dug in further I decided to update just copilot.lua directly (lowercase "u" in the Lazy.nvim UI) and THAT caused it to pick this patch up 🤷 . 

Let me know if you'd like the notes I took about what I was seeing and all of the things I went through and tried if it will help you when you do come back to this someday! Thanks for the work on this plugin - massively appreciated.

**Comment by magnusriga** [comment]
It is not necessary to depend on `lspconfig`. I would leave the cwd as the default, but allow users to pass a function.

Setting root_config can be done during setup, then later, when the autocmd is run, it can call the function to resolve the path.

Here is how `lspconfig` does it, which is a relatively simple fix to add here: https://github.com/neovim/nvim-lspconfig/blob/919f83ef8169d11eabd921a4cbda4fc1ba12f123/lua/lspconfig/manager.lua#L203

As s side note, to get the `.git` ancestor (git root path), you do not need to use any third party functions. This works fine:

```lua
﻿root_dir = function(start)
  return vim.fs.dirname(vim.fs.find(".git", { path = start, upward = true })[1])\
end
```

(of course, the search pattern, i.e. `.git` above, should be passed in from the config).

**Pull request merged**
