### PR TITLE
feat: add copilot.api module

### PR DESCRIPTION
**Pull request by MunifTanjim**
## Description

- util changes to follow the `copilot.vim` behavior closely
- ~panel changes to make it more extensible~
- `copilot.api` module can be used by any plugins that want to implement UI for `copilot.lua`

## Using the `copilot.api` module

The APIs can be used in two flavors:

**Callback**

```lua
local sent, request_id = require("copilot.api").check_status(client, function(err, data, ctx)
  print(vim.inspect({ err = err, data = data, ctx = ctx })
end)
```

**Coroutine**

```lua
coroutine.wrap(function()
  local err, data, ctx = require("copilot.api").check_status(client)
  print(vim.inspect({ err = err, data = data, ctx = ctx })
end)()
```

---

I'll be creating followup PRs to make the panel fully functional.

### CODE REVIEW

**Comment by zbirenbaum** [comment]
Does this maintain functionality of using PanelSolutions for copilot-cmp?

**Comment by MunifTanjim** [comment]
> Does this maintain functionality of using PanelSolutions for copilot-cmp?

I didn't remove any functions, only marked them as `---@deprecated` and changed the function body to use the new codes.

So it should keep working, although I haven't tested yet.

**Comment by zbirenbaum** [comment]
> > Does this maintain functionality of using PanelSolutions for copilot-cmp?
> 
> I didn't remove any functions, only marked them as `---@deprecated` and changed the function body to use the new codes.
> 
> So it should keep working, although I haven't tested yet.

Ok, sounds good. I quickly looked over the changes here and in the other PRs and I liked what I saw but I'll have to go through them more in depth tomorrow or over the weekend since I'm really busy with a project for work atm. Thanks so much for making all these PRs, it's a massive help!

**Comment by MunifTanjim** [comment]
@zbirenbaum updated the PR to add all the APIs for copilot in the `copilot.api` module.

Multiple plugins can now listen to `PanelSolution`, `PanelSolutionsDone` and `statusNotification` handlers without conflicting with each other.

**Comment by zbirenbaum** [comment]
Hi @MunifTanjim thanks so much for making these PRs. I got to a pausing point on the project I was assigned at work and trying to review your patches. Is there a specific merge order you have in mind? While testing this PR I noticed errors from references to functions added in #50

**Comment by MunifTanjim** [comment]
I think this PR #48 should be reviewed and merged first.

After that I can rebase the other 2 and you can review them independently.

**Review by zbirenbaum — COMMENTED** [review]
The functions in handlers.lua reference functions that are added in the panel pr. They are called by copilot-cmp for some configurations causing an error. I'm not sure it's a great idea to reference functions that don't exist even if they will be added later.

Could you revert the state of handlers.lua and include the changes to it as part of the panel pr?

**Comment by zbirenbaum** [comment]
> The functions in handlers.lua reference functions that are added in the panel pr. They are called by copilot-cmp for some configurations causing an error. I'm not sure it's a great idea to reference functions that don't exist even if they will be added later.

Could you revert the state of handlers.lua and include the changes to it as part of the panel pr?

**Comment by MunifTanjim** [comment]
Hmm... I removed the all the changes related to panel from this PR. `copilot-cmp` should be okay for now.

But at some point we need to do breaking changes with `copilot-cmp` and open a PR in `copilot-cmp` to fix it.

**Comment by MunifTanjim** [comment]
> They are called by copilot-cmp for some configurations causing an error

I can't reproduce this tho. Can you share any specific config for which `copilot-cmp` is not working? I can open a patch PR there.

**Comment by zbirenbaum** [comment]
> > They are called by copilot-cmp for some configurations causing an error
> 
> 
> 
> I can't reproduce this tho. Can you share any specific config for which `copilot-cmp` is not working? I can open a patch PR there.

Sorry I don't know why but I didn't get a notification for this. I think what I'll do is just move the old code over to copilot-cmp and once everything is done I'll change it to use the new api. I really doubt anyone is using that particular feature anyways because while it was super useful at one point, Microsoft made some change that slowed it down dramatically so it's nearly unusable... I'll merge this tonight and start going over the others

**Review by zbirenbaum — APPROVED** [review]

**Comment by zbirenbaum** [comment]
Looks good. The config option that caused the issue was setting `method = "getPanelCompletions",` for reference, but I pushed an update making it independent. Its still definitely good to not have code referencing functions not yet merged though, so thanks for making the change!

**Comment by MunifTanjim** [comment]
>  Its still definitely good to not have code referencing functions not yet merged though, so thanks for making the change!

Now that I'm rebasing, I see what you mean. That was a mistake 😂 I was supposed to require `copilot.api` in the `copilot.handlers` module. But I did refactor the PRs multiple times and just forgot to update `copilot.handlers`.

**Pull request merged**
